=== GeoDienstenCentrum/CBSviewer/src/main/xsd/AvailableLayers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://xml.util.cbsviewer.mineleni.nl" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:version="2.0" attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:l="http://xml.util.cbsviewer.mineleni.nl">
	
	<xs:element name="Layers" type="l:layersList">
		<xs:annotation>
			<xs:documentation>Beschrijft een verzameling van kaartlagen.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:complexType name="layersList">
		<xs:sequence>
			<xs:element name="Layerdescriptor" type="l:layerDescriptor"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="layerDescriptor">
		<xs:annotation>
			<xs:documentation>Beschrijft een kaart laag voor de applicatie. Een
				laag kan bestaan uit 1 of meer lagen van 1 WMS.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="xs:string" name="id" nillable="false"
				minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>unieke identifier van deze kaartlaag
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="name" nillable="false"
				minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>beschrijvende naam van deze kaartlaag
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="layers" nillable="false"
				minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Een kommagescheiden string met een of meer namen
						van de LAYERS van de WMS</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:anyURI" name="url" nillable="false"
				minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>De base URL van de WMS waar deze kaartlaag uit
						opgebouwd wordt.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="styles" nillable="false"
				minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>De lijst met STYLES, een kommagescheiden string
						met een of meer namen van de styles van de WMS. Het aantal moet
						gelijk zijn aan het aantal lagen.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="attributes" nillable="false"
				minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>De te tonen feature attributen als resultaat van
						een FeatureInfo request. Kommagescheiden.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== GeoDienstenCentrum/CBSviewer/src/test/resources/AvailableLayers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Layers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://xml.util.cbsviewer.mineleni.nl" xsi:schemaLocation="http://xml.util.cbsviewer.mineleni.nl AvailableLayers.xsd">
	<Layerdescriptor>
		<id>vierkanten500m_oad2000</id>
		<name>Vierkant 500m - Omgevingsadressendichtheid 2000</name>
		<layers>omgevings_adres_dichtheid_2000</layers>
		<url>http://geodata.nationaalgeoregister.nl/cbsvierkanten500m/wms</url>
		<styles>cbsvierkanten500m.oad2000</styles>
		<attributes>oad2000</attributes>
		<aliases>dichtheid</aliases>
	</Layerdescriptor>
	<!-- START SNIPPET: layermodel_apt_1 -->
	<Layerdescriptor>
		<id>wijkenbuurten2011_thema_gemeenten2011_aantal_inwoners</id>
		<name>CBS Gemeenten 2011 - Aantal inwoners</name>
		<layers>gemeenten2011</layers>
		<url>http://geodata.nationaalgeoregister.nl/wijkenbuurten2011/wms</url>
		<styles>wijkenbuurten2011_thema_gemeenten2011_aantal_inwoners</styles>
		<attributes>aantal_inwoners, gemnaam</attributes>
		<aliases>aantal_inwoners, gemeente</aliases>
		<link>http://geodata.nationaalgeoregister.nl/wijkenbuurten2011/wfs?request=GetFeature&amp;typeName=wijkenbuurten2011:gemeenten2011&amp;outputFormat=SHAPE-ZIP</link>
	</Layerdescriptor>
	<!-- START SNIPPET: layermodel_apt_1 -->
</Layers>

=== GeoDienstenCentrum/CBSviewer/src/main/resources/AvailableLayers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Layers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://xml.util.cbsviewer.mineleni.nl" xsi:schemaLocation="http://xml.util.cbsviewer.mineleni.nl AvailableLayers.xsd ">
	<Layerdescriptor>
		<id>cbs_inwoners_2000_per_hectare</id>
		<name>inwoners 2000 per hectare</name>
		<layers>inwoners_2000</layers>
		<url>http://geodata.nationaalgeoregister.nl/cbsvierkanten100m/ows</url>
		<styles>cbsvierkanten100m_inw2000</styles>
		<attributes>inw2000</attributes>
	</Layerdescriptor>
	<Layerdescriptor>
		<id>toename_inwoners_2000_2010</id>
		<name>verandering inwoners 2000-2010</name>
		<layers>toename_inwoners_2000_2010</layers>
		<url>http://geodata.nationaalgeoregister.nl/cbsvierkanten100m2010/ows</url>
		<styles>cbsvierkanten100m_tinw_10_00</styles>
		<attributes>gid,tinw_10_00</attributes>
	</Layerdescriptor>
</Layers>
